services:
  - type: web
    name: quiz-generator-api
    runtime: python3
    buildCommand: pip install -r apps/backend/requirements.txt
    startCommand: cd apps/backend && python -m fastapi run main.py --host 0.0.0.0 --port $PORT
    plan: free
    healthCheckPath: /health
    envVars:
      - key: OPENAI_API_KEY
        sync: false # Set manually in Render dashboard
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: "*"
    rootDir: apps/backend
    branch: main
    scaling:
      minInstances: 0
      maxInstances: 1 